version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: 'mysql:5.7'
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: main
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    ports:
      - '4306:3306'
    volumes:
      - mysql_storage:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  mysql_storage:
###< doctrine/doctrine-bundle ###
